CREATE TABLE "GCG_4939_SAME_DAY"(
 "CUSTOMER" CHAR(6),
 "NAME_CUSTOMER" CHAR(30),
 "CUSTOMER_PO" CHAR(15),
 "ORDER_NO" CHAR(7),
 "ORDER_LINE" CHAR(4),
 "DATE" DATE,
 "PART" CHAR(17),
 "REV" CHAR(3));


